-- PRODUCT ANALYSIS 
/*
PRODUCT SALES ANALYSIS 
ANALYZING PRODUCT SALES HELPS TO UNDERSTAND HOW EACH PRODUCT CONTRIBUTES TO OUR BUSINESS AMD HOW PRODUCT 
LAUNCHES IMPACT THE OVERALL PORTFOLIO
*/

-- ANALYZING PRODUCT SALES AND PRODUCT LAUNCHES 

SELECT
   primary_product_id,
   COUNT(order_id) AS orders,
   SUM(price_usd) AS revenue,
   SUM(price_usd - COGS_USD) AS margin,
   AVG(price_usd) AS average_order_value 
FROM orders
WHERE order_id BETWEEN 10000 AND 11000
GROUP BY 1
ORDER BY 2 DESC;